Fix the potential bug
ERROR deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.134.0. Use hugo.IsServer instead.
Total in 441 ms
Error: error building site: logged 1 error(s)